name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        meteor: [1.12.3, 2.3.1, 2.9.1, 2.12]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Meteor
        uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: ${{ matrix.meteor }}
      - name: Tests
        run: |
          meteor test-packages ./
